### ISSUE TITLE
Custom component works fine in interactive context but fails when executed using Airflow/Beam

### ISSUE THREAD

**Issue by ismail-dinar** [tensorflow/tfx#1701]
I've created a custom component that ingest data from MySql Database using the package beam-mysql-connector and it works really fine in interactive context but when i try to run it using airflow or beam I get the following error.

Traceback (most recent call last):
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 170, in _execute
    response = task()
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 203, in <lambda>
    self._execute(lambda: worker.do_instruction(work), work)
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 360, in do_instruction
    request.instruction_id)
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/sdk_worker.py", line 386, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 663, in process_bundle
    data.transform_id].process_encoded(data.data)
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/runners/worker/bundle_processor.py", line 143, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 255, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 256, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 143, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 593, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/worker/operations.py", line 594, in apache_beam.runners.worker.operations.DoOperation.process
  File "apache_beam/runners/common.py", line 776, in apache_beam.runners.common.DoFnRunner.receive
  File "apache_beam/runners/common.py", line 782, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 849, in apache_beam.runners.common.DoFnRunner._reraise_augmented
  File "/home/doblatrobla/new/lib/python3.6/site-packages/future/utils/__init__.py", line 446, in raise_with_traceback
    raise exc.with_traceback(traceback)
  File "apache_beam/runners/common.py", line 780, in apache_beam.runners.common.DoFnRunner.process
  File "apache_beam/runners/common.py", line 441, in apache_beam.runners.common.SimpleInvoker.invoke_process
  File "/home/doblatrobla/new/lib/python3.6/site-packages/apache_beam/io/iobase.py", line 871, in split_source
    self.get_desired_chunk_size(self.source.estimate_size()))
  File "/home/doblatrobla/new/lib/python3.6/site-packages/beam_mysql/connector/source.py", line 49, in estimate_size
    return self._splitter.estimate_size()
  File "/home/doblatrobla/new/lib/python3.6/site-packages/beam_mysql/connector/splitters.py", line 48, in estimate_size
    return self.source.client.rough_counts_estimator(self.source.query)
AttributeError: 'NoSplitter' object has no attribute 'source' [while running 'InputToSerializedExample/InputSourceToExample/ReadFromMySQL/Read/Split']
 [while running 'Run[MySqlQueryExampleGen]']`

**Comment by ismail-dinar** [comment]
This error is related to the package beam-mysql-connector and apache-beam version. It works fine with apache-beam 2.16.0 but it fails when using either apache-beam 2.18.0 or 2.17.0.

**Comment by ismail-dinar** [comment]
After running some test I found that the error is not related to the package  beam-mysql-connector. 
When I run the pipeline using only 1 process for beam pipeline execution it works fine and when I use more than one process it fails. So from what I understand I think that using multiple processes causes conflict in the order at which the code has to be executed. 
I hope someone can help me.

**Comment by zhitaoli** [comment]
@ismail-dinar : Are you able to use direct worker with single thread, at least for this component, if that could satisfy your need?

Otherwise, you might want to consult user@beam.apache.org for the question, or checkout this related page:

Please also take a look at this page to see if it helps: https://beam.apache.org/documentation/runners/direct/

**Comment by ismail-dinar** [comment]
Well, I was able to run the pipeline with a single thread without having any error. 
Running with a single thread doesn't represent any problem for the time being.

**Comment by gaikwadrahul8** [comment]
@ismail-dinar 

Apologies for the delay and just to confirm, are you still facing the same issue while running custom component with the help of Airflow ? if yes could you please help me with your minimal code to reproduce the same error with Airflow ? As you have confirmed above you're able to run custom component with the help of Apache Beam with single thread and if you're looking to try with multiple thread then please go through Apache Beam Programming Guide [here](https://beam.apache.org/documentation/programming-guide/#user-code-thread-compatibility) and I would suggest you to please go with latest version of Apache Beam and if you're looking to run custom component through Airflow then please follow our official documentation [here](https://www.tensorflow.org/tfx/tutorials/tfx/airflow_workshop)

Thank you!

**Comment by gaikwadrahul8** [comment]
Closing this due to inactivity. Please take a look into above workaround, Please feel free to re-open the issue if necessary and post your comments(if you still have queries on this). Thank you!
